DataBundle\Entity\Attachmentstargets: 
  type:  entity
  id: 
    id: 
      type:  integer
      generator: 
        strategy:  AUTO
  manyToOne: 
    attachments: 
      targetEntity:  Attachments
      inversedBy:  attachmentstargets
      joinColumn: 
        name:  attachments_id
        referencedColumnName:  id
  table:  attachmentstargets
  fields: 
    target: 
      type:  integer
    entity: 
      type:  string
      length:  100
    description: 
      type:  string
      length:  256
      nullable:  true
    