DataBundle\Entity\Configs: 
    type:  entity
    id: 
        id: 
            type:  integer
            generator: 
                strategy:  AUTO
    table:  configs 
    fields: 
        logo: 
            type:  string
            length: 256
        name: 
            type:  string
            length: 256
        slogan:
            type: string
            length: 256
        about:
            type: text
        tel:
            type: string
            length: 25
        mobile:
            type: string
            length: 25
        skype:
            type: string
            length: 128
        email:
            type: string
            length: 128
        address:
            type: string
            length: 256
        latitude:
            type: string
            length: 256
        longitude:
            type: string
            length: 256
        