DataBundle\Entity\ContestsQuestionsDatas: 
  type:  entity
  table:  contestsquestionsdatas
  id: 
   id: 
      type:  integer
      id:  true
      generator: 
        strategy:  AUTO
  manyToOne: 
    questions: 
        targetEntity:  Questions
        inversedBy:  questionsdatas
        joinColumn: 
            name:  questions_id
            referencedColumnName:  id
  fields: 
   index: 
      type:  string
      length:  50
   value: 
      type:  string
      length:  100