DataBundle\Entity\EmailsAttachments: 
  type:  entity
  manyToOne: 
    emails: 
      targetEntity:  Emails
      inversedBy:  emailsattachments
      joinColumn: 
        name: emails_id
        referencedColumnName: id
    files: 
      targetEntity:  Files
      inversedBy:  emailsattachments
      joinColumn: 
        name: files_id
        referencedColumnName: id
      cascade:
            ['remove']
  table:  emailsattachments
  id: 
    id: 
      type:  integer
      id:  true
      generator: 
        strategy:  AUTO
  fields:  