DataBundle\Entity\EmailsAttachments: 
  type:  entity
  manyToOne: 
    emails: 
      targetEntity:  Emails
      inversedBy:  emailsattachments
      joinColumn: 
        name: emails_id
        referencedColumnName: id
  oneToMany: 
    previews: 
      targetEntity:  Previews
      mappedBy:  files
      cascade:
            ['remove']
  table:  emailsattachments
  id: 
    id: 
      type:  integer
      id:  true
      generator: 
        strategy:  AUTO
  fields: 
    file_path: 
      type:  string
    file_format:
      type: string
      nullable: true
    file_name:
      type: string
      nullable: true
    thumbnail: 
      type:  string
      nullable:  true