DataBundle\Entity\FacultiesTeachers: 
  type:  entity
  manyToOne: 
    faculties: 
      targetEntity:  Faculties
      inversedBy:  facultiesteachers
      joinColumn: 
          name:  faculties_id
          referencedColumnName:  id
    users: 
      targetEntity:  Users
      inversedBy:  facultiesteachers
      joinColumn: 
        name: users_id
        referencedColumnName: id
    facultiesteachersvalidate:
      targetEntity:  Users
      inversedBy:  facultiesteachersvalidate
      joinColumn: 
        name: validate_users_id
        referencedColumnName: id
  table:  facultiesteachers
  uniqueConstraints:
        uniqueConstraint:
            columns: [users_id, faculties_id]
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO
  fields: 