DataBundle\Entity\FacultiesViceAdministrators: 
  type:  entity
  manyToOne: 
    faculties: 
      targetEntity:  Faculties
      inversedBy:  facultiesviceadministrators
      joinColumn: 
          name:  falculties_id
          referencedColumnName:  id
    users: 
      targetEntity:  Users
      inversedBy:  facultiesviceadministrators
      joinColumn: 
        name: users_id
        referencedColumnName: id
    facultiesviceadministratorsvalidate: 
      targetEntity:  Users
      inversedBy:  facultiesviceadministratorsvalidate
      joinColumn: 
        name: validate_users_id
        referencedColumnName: id
  table:  facultiesviceadministrators
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO
  fields: 