DataBundle\Entity\FilesFormats: 
  type:  entity
  oneToMany: 
    files: 
      targetEntity:  Files
      mappedBy:  filesformats
  table:  filesformats
  id: 
   id: 
      type:  integer
      id:  true
      generator: 
        strategy:  AUTO
  fields: 
   name: 
      type:  string
      length:  150
   description: 
      type:  text
      nullable:  true
   icon:  
      type:  string
      length:  150