DataBundle\Entity\FilesTags: 
    type:  entity
    id: 
       id: 
            type:  integer
            generator: 
                strategy:  AUTO
    oneToMany: 
        files: 
            targetEntity:  Files
            mappedBy:  filestags
    manyToOne: 
        users: 
            targetEntity:  Users
            inversedBy:  filestags
            joinColumn:  
              name: users_id
              referencedColumnName: id
    table:  filestags 
    fields:  
       name: 
            type:  string
            length:  150
       description: 
            type:  text
            nullable: true        