DataBundle\Entity\Ips: 
    type:  entity
    id: 
       id: 
            type:  integer
            generator: 
                strategy:  AUTO
    manyToOne: 
        users: 
            targetEntity:  Users
            inversedBy:  ips
            joinColumn: 
                name: users_id
                referencedColumnName: id
    table:  ips
    fields: 
       ip: 
            type:  string
            length:  50     
    uniqueConstraints: 
        uip: 
            columns:  [id,ip] 
        