DataBundle\Entity\News: 
    type:  entity
    id: 
        id: 
            type:  integer
            generator: 
                strategy:  AUTO
    manyToOne: 
        newscategories: 
            targetEntity:  NewsCategories
            inversedBy:  news
            joinColumn: 
                name:  newscategories_id
                referencedColumnName:  id
    table:  news 
    fields: 
        thumbnail:
            type: text
            nullable: true
        title: 
            type:  string
            length: 256
        intro:
            type: string
            length: 256
        content:
            type: text
        time:
            type: string
            length: 25
            nullable: true
        