DataBundle\Entity\NewsCategories: 
    type:  entity
    id: 
        id: 
            type:  integer
            generator: 
                strategy:  AUTO
    oneToMany: 
        news: 
          targetEntity:  News
          mappedBy:  newscategories
    table:  newscategories 
    fields: 
        name: 
            type:  string
            length: 256 
        active: 
            type:  integer
        
            
        