DataBundle\Entity\OptionsPricesIncrements: 
    type:  entity
    id: 
     id: 
        type:  integer
        generator: 
          strategy:  AUTO
    manyToOne: 
        pickuplocations: 
            targetEntity:  Locations
            inversedBy:  optionspricesincrements
            joinColumn: 
                name:  pickup_locations_id
                referencedColumnName:  id
        deliverylocations: 
            targetEntity:  Locations
            inversedBy:  optionspricesincrements
            joinColumn: 
                name:  delivery_locations_id
                referencedColumnName:  id 
        services: 
            targetEntity:  Services
            inversedBy:  optionspricesincrements
            joinColumn: 
                name:  services_id
                referencedColumnName:  id 
    table:  optionspricesincrements
    fields:  
        increase: 
            type:  integer
        
   