DataBundle\Entity\Orders: 
    type:  entity
    id: 
        id: 
            type:  integer
            generator: 
                strategy:  AUTO
    manyToOne: 
        users: 
            targetEntity:  Users
            inversedBy:  orders
            joinColumn: 
                name:  users_id
                referencedColumnName:  id
    oneToMany: 
        parcels: 
          targetEntity:  Parcels
          mappedBy:  orders
    table:  orders 
    fields: 
        status: 
            type:  string
            length: 256
        
            
        