DataBundle\Entity\Phrasescontents: 
  type:  entity
  table:  phrasescontents
  manyToOne: 
    phrases: 
      targetEntity:  Phrases
      inversedBy:  phrasescontents
      joinColumn: 
        name:  ph_id
        referencedColumnName:  ph_id
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO  
  fields: 
   content: 
      type:  string
      length:  255
   language: 
      type:  string
  

  


  
