DataBundle\Entity\PostsCourses: 
  type:  entity
  manyToOne: 
    posts: 
      targetEntity:  Posts
      inversedBy:  postscourses
      joinColumn: 
        name:  posts_id
        referencedColumnName:  id
    courses: 
      targetEntity:  Courses
      inversedBy:  postscourses
      joinColumn: 
        name: courses_id
        referencedColumnName: id
  table:  postscourses
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO
  fields: 
   visible: 
      type:  integer
   sharing: 
      type:  integer
   follow: 
      type:  string
   un_follow: 
      type:  string