DataBundle\Entity\PostsImages: 
  type:  entity
  manyToOne: 
    posts: 
      targetEntity:  Posts
      inversedBy:  postsimages
      joinColumn: 
        name:  posts_id
        referencedColumnName:  id
    images: 
      targetEntity:  Images
      inversedBy:  postsimages
      joinColumn: 
        name: images_id
        referencedColumnName: id
  table:  postsimages
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO
  fields: 
   visible: 
      type:  integer
   sharing: 
      type:  integer
   order: 
      type:  integer
      nullable:  true