DataBundle\Entity\PostsDatas: 
  type:  entity
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO
  manyToOne: 
    posts: 
      targetEntity:  Posts
      inversedBy:  postsdatas
      joinColumn: 
        name:  posts_id
        referencedColumnName:  id
  table:  postsdatas
  fields: 
   index: 
      type:  string
   value: 
      type:  text