DataBundle\Entity\PostsTypes: 
  type:  entity
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO
  oneToMany: 
    posts: 
      targetEntity:  Posts
      mappedBy:  poststypes
  table:  poststypes
  fields: 
   name: 
      type:  string
      length:  100
   description: 
      type:  text