DataBundle\Entity\Previews: 
    type:  entity
    id: 
        id: 
            type:  integer
            generator: 
                strategy:  AUTO
    manyToOne: 
        files: 
            targetEntity:  Files
            inversedBy:  previews
            joinColumn: 
                name:  files_id
                referencedColumnName:  id
    table:  previews
    fields: 
        filepath: 
            type:  string
            length: 256
        