DataBundle\Entity\PricesIncrements: 
    type:  entity
    id: 
     id: 
        type:  integer
        generator: 
          strategy:  AUTO
    manyToOne: 
        pickuplocations: 
            targetEntity:  Locations
            inversedBy:  prices
            joinColumn: 
                name:  pickup_locations_id
                referencedColumnName:  id
        deliverylocations: 
            targetEntity:  Locations
            inversedBy:  prices
            joinColumn: 
                name:  delivery_locations_id
                referencedColumnName:  id
    table:  pricesincrements
    fields:  
        block: 
            type:  integer
        price: 
            type:  integer
        collect:
            type:  integer
            nullable: true
        alarm:
            type:  integer
            nullable: true

   