DataBundle\Entity\RightAnswersTrueFalse: 
    type:  entity
    id: 
        id: 
            type:  integer
            generator: 
                strategy:  AUTO
    manyToOne: 
        questions: 
            targetEntity:  Questions
            inversedBy:  rightanswerstruefalse
            joinColumn: 
                name:  questions_id
                referencedColumnName:  id
    table:  rightanswerstruefalse
    fields: 
        content: 
            type:  text
        