DataBundle\Entity\SchoolsTeachers: 
  type:  entity
  manyToOne: 
    schools: 
      targetEntity:  Schools
      inversedBy:  schoolsteachers
      joinColumn: 
        name: schools_id
        referencedColumnName: id
    users: 
      targetEntity:  Users
      inversedBy:  schoolsteachers
      joinColumn: 
        name: users_id
        referencedColumnName: id
  table:  schoolsteachers
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO
  fields: 
   status: 
      type:  string
      length:  256
      nullable:  true
   join_date: 
      type:  integer
      nullable:  true
   role:  
      type:  string
   proof: 
      type:  string
      nullable:  true