DataBundle\Entity\TeachingSubjects: 
  type:  entity
  manyToOne: 
    subjects: 
      targetEntity:  Subjects
      inversedBy:  teachingsubjects
      joinColumn: 
        name: subjects_id
        referencedColumnName: id
    users: 
      targetEntity:  Users
      inversedBy:  teachingsubjects
      joinColumn: 
        name: users_id
        referencedColumnName: id
  table:  teachingsubjects
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO