DataBundle\Entity\TestsTypesSubjects: 
    type:  entity
    manyToOne: 
        subjects: 
            targetEntity:  Subjects
            inversedBy:  teststypessubjects
            joinColumn: 
              name: subjects_id
              referencedColumnName: id
        teststypes: 
            targetEntity:  TestsTypes
            inversedBy:  teststypessubjects
            joinColumn: 
              name: teststypes_id
              referencedColumnName: id
    table:  teststypessubjects
    id: 
       id: 
            type:  integer
            generator: 
              strategy:  AUTO
    fields: 
       quantity: 
            type:  integer
            nullable:  true