DataBundle\Entity\TransactionsDatas: 
  type:  entity
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO
  manyToOne: 
    transactions: 
      targetEntity:  Transactions
      inversedBy:  transactionsdatas
      joinColumn: 
        name: transactions_id
        referencedColumnName: id
  table:  transactionsdatas
  fields: 
   index: 
      type:  string
   value: 
      type:  string