DataBundle\Entity\UsersWalls: 
  type:  entity
  manyToOne:
    users: 
      targetEntity:  Users
      inversedBy:  userswalls
      joinColumn: 
        name: users_id
        referencedColumnName: id
    posts: 
      targetEntity:  Posts
      inversedBy:  userswalls
      joinColumn: 
        name: posts_id
        referencedColumnName: id
  table:  userswalls
  id: 
   id: 
      type:  integer
      generator: 
        strategy:  AUTO
  fields: 
   home: 
      type:  boolean
   private: 
      type:  boolean
   follow: 
      type:  string
      nullable: true
   un_follow:  
      type:  string
      nullable: true