app:
    resource: "@AppBundle/Controller/"
    type:     annotation
home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
teacher:
    resource: "@TeacherBundle/Controller/"
    type:     annotation
