security:
    encoders:
        DâtBundle\Entity\Users:
            algorithm: bcrypt

    # ...

    providers:
        our_db_provider:
            entity:
                class: DataBundle:Users
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous:    ~
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
    
